version: '2'
services:
  zkecowebservice:
    build:
      context: .
      dockerfile: Dockerfile-zkeco-webservice
      args:
        ZK_DATABASE_HOST: "192.168.2.99"
        #ZK_DATABASE_PORT: 3306
        #ZK_DATABASE_NAME: zkeco_db
        #ZK_DATABASE_USER: zkeco
        ZK_DATABASE_PASS: "c3"
    ports:
      - 5000
      - "8000:8000"
    links: 
      - zkecomysql
#      - zkecomemcachedservice

  zkecomysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql-utf8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "zkeco"
      MYSQL_PASSWORD: "c3"
      MYSQL_DATABASE: "zkeco_db"

#  zkecomemcachedservice:
#    image: memcached

